language: objective-c
osx_image: xcode9
script:
 - xcodebuild -project AutoclosureAndEscaping.xcodeproj -scheme AutoclosureAndEscaping clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest'

